name: .NET

on:
  push:
  pull_request:

jobs:
  backend:
    defaults:
       run:
          shell: bash
          working-directory: ./src/backend/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.4.21255.9
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  frontend:
    defaults:
        run:
           shell: bash
           working-directory: ./src/frontend/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
          node-version: 16.30
    - name: Install yarn
      run: npm install -g yarn
    - name: Run yarn install
      run: yarn install
    - name: Run yarn build
      run: yarn build
    - name: Run yarn test
      run: yarn test
     